---

- name: "GET SNMP CONFIGURATION"
  register: get_snmp_config
  ios_command:
    provider: "{{ cli }}"
    commands:
      - "show running-config | include snmp-server host"


- name: "REMOVE SNMP CONFIG"
  when: get_snmp_config.stdout_lines[0][0] != ""
  ios_config:
    provider: "{{ cli }}"
    lines:
      - "no snmp-server"

- name: "SET SNMP CONFIG"
#  when: "(ntp_vars.timezone is defined) and (ntp_vars.timezone != get_ntp_config.stdout_lines[0][0])"
  with_items: "{{ snmp_vars.snmp_server }}"
  register: set_snmp_server
  ios_config:
    provider: "{{ cli }}"
    lines:
      - "{{ item }}"

- name: "GET SNMP ENGINEID"
  register: get_snmp_engineID
  ios_command:
    provider: "{{ cli }}"
    commands:
      - "show snmp engineID"

- name: "SET SNMP ENGINEID"
  when: "get_snmp_engineID.changed == true"
  register: set_snmp_engineID
  ios_config:
    provider: "{{ cli }}"
    lines:
      - "{{ snmp_vars.snmp_engineID }} get_snmp_engineID.stdout_lines[0][2].split('\t')[0]"

- name: "SET NO SNMP CONFIG"
  with_items: "{{ snmp_vars.no_snmp_server }}"
  register: set_no_snmp_server
  ios_config:
    provider: "{{ cli }}"
    lines:
      - "{{ item }}"
