---

- name: Run cfg commands on switches
  hosts: test
  gather_facts: false
  connection: local

  tasks:

    - name: Save config
      ios_command:
        commands: 
          - write
        provider: "{{ cli }}"
#      when: cfg.changed

